### PR TITLE
Add UGALY package to the distribution

### PR DESCRIPTION
**Pull request by laurentbartholdi**
Added UGALY

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@laurentbartholdi Thanks (CC @torniers)

**Comment by fingolfin** [comment]
This is not going to work, see https://github.com/gap-packages/UGALY/pull/2

**Comment by alex-konovalov** [comment]
Thanks @fingolfin - it was picked up, but it will not work next time of course, until the fix and new version released. 

Maybe Jenkins tests now will uncover more suggestions, let's wait for a few hours.

**Comment by alex-konovalov** [comment]
reenabled UGALY again in f6025d7c4ab8034dd9fda72ff89bc8fd3e9a822a

**Comment by fingolfin** [comment]
I see UGALY listed on https://github.com/gap-system/gap/wiki/Package-updates-status as well but it doesn't appear to be in the actual package archive?

**Comment by alex-konovalov** [comment]
You're right, it will hopefully appear when the next update of the package archive will happen. I have now 4.0.1 version picked up, waiting for the next Jenkins testing cycle to complete.

**Comment by alex-konovalov** [comment]
It's now included in https://github.com/gap-system/gap-distribution/releases/tag/package-archives

**Pull request merged**
