### PR TITLE
Add RepnDecomp to PackageInfo.g list

### PR DESCRIPTION
**Pull request by kaashif**
This is my package, with a submission to https://joss.theoj.org/ being reviewed here: https://github.com/openjournals/joss-reviews/issues/1835. @alex-konovalov is one of the reviewers and advised me to open this PR here.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Thanks @kaashif. I run some preliminary tests. First, for the reference, this is an overview from `make testpackagesvars` output:
```
### Checking variables in "repndecomp", ver. 1.0.1
new global functions:
  AreRepsIsomorphic( rep1, rep2 )
  BasisChangeMatrixSimilar( X, Y )*
  BlockDiagonalBasisOfRepresentation( rho )
  BlockDiagonalMatrix( blocks )
  BlockDiagonalRepresentation( rho )
  CanonicalDecomposition( rho )
  CentralizerBlocksOfRepresentation( rho )
  CentralizerOfRepresentation( rho )
  CharacterOfTensorProductOfRepresentations( rho )
  ClassSumCentralizer( rho, class, cent_basis )
  ClassSumCentralizerNC( rho, class, cent_basis )
  ComposeHomFunction( hom, func )
  DegreeOfRepresentation( rep )
  DirectSumOfRepresentations( reps )
  GroupSumBSGS( G, summand )
  IrreducibleDecomposition( rho )
  IrreducibleDecompositionCollected( rho )
  IrreducibleDecompositionDixon( rho )
  IsLinearRepresentationIsomorphism( A, rho, tau )
  IsOrthonormalSet( S, prod )
  IsUnitaryRepresentation( rho )
  KroneckerProductOfRepresentations( rho, tau )*
  LDLDecomposition( A )
  LinearRepresentationIsomorphism(  )
  LinearRepresentationIsomorphismSlow(  )
  PermToLinearRep( rho )
  Replicate( arg )
  SizesToBlocks( sizes )*
  TensorProductOfMatrices( A, B )
  TensorProductOfMatricesFamily( dimA, dimB )*
  TensorProductOfMatricesObj( Fam, A, B )*
  TensorProductOfRepresentations( rho, tau )*
  TensorProductRepLists( reps1, reps2 )
  UnitaryRepresentation( rho )

new attributes:
  IsFiniteGroupLinearRepresentation( ... )
  IsFiniteGroupPermutationRepresentation( ... )
  REPN_ComputeUsingMyMethod( ... )
  REPN_ComputeUsingMyMethodCanonical( ... )
  REPN_ComputeUsingSerre( ... )

new categories:
  IsTensorProductOfMatricesObj( ... )

new representations:
  IsTensorProductKroneckerRep( ... )
  IsTensorProductPairRep( ... )

new methods:
  *( prod, A )*
    for applying tensor products to matrices
  *( x, y )*
    for tensor products of matrices
  =( x, y )*
    for tensor products of matrices
  InverseMutable( x )
    for tensor products of matrices
  IsFiniteGroupLinearRepresentation( rho )
    checks if rho is a linear rep of finite group
  IsFiniteGroupPermutationRepresentation( rho )
    finite to perm group
  IsGeneratorsOfMagmaWithInverses( coll )*
    for tensor products of matrices
  OneMutable( x )
    for tensor products of matrices
  PrintObj( x )
    for tensor products of matrices
  REPN_ComputeUsingMyMethod( rho )
    for linear reps
  REPN_ComputeUsingMyMethodCanonical( rho )
    for linear reps
  REPN_ComputeUsingSerre( rho )
    for linear reps

other new globals (not write protected):
  BasisChangeMatrix@RepnDecomp( rho )*
  BasisChangeMatrixSimilar@RepnDecomp( X, Y )*
  BenchList@RepnDecomp( f, rhos, out, irreps )*
  BenchMany@RepnDecomp( f, out, n, opt )*
  BenchSingle@RepnDecomp( f, out, rep )*
  BlocksOfMat@RepnDecomp( P, M )*
  CCAggregateBasisMat@RepnDecomp( TN )*
  CCBasisMats@RepnDecomp( TN )*
  CCCoeff@RepnDecomp( TN, a, b, c )*
  CCCountByLeftFiber@RepnDecomp( TN, I )*
  CCDegree@RepnDecomp( T )*
  CCDimension@RepnDecomp( TN )*
  CCElementContainingPair@RepnDecomp( TN, pair )*
  CCElementSize@RepnDecomp( T, t )*
  CCFiberSizes@RepnDecomp( T )*
  CCGlobalIndex@RepnDecomp( TN, lnum )*
  CCGroup@RepnDecomp( T )*
  CCIntersectionMat@RepnDecomp( TN, b )*
  CCIntersectionMatCOO@RepnDecomp( TN, b )*
  CCIntersectionMatLIL@RepnDecomp( TN, b )*
  CCIntersectionMats@RepnDecomp( TN )*
  CCIntersectionMatsCOO@RepnDecomp( TN )*
  CCLocalIndex@RepnDecomp( TN, i )*
  CCNumFibers@RepnDecomp( TN )*
  CCPopulateCoeffs@RepnDecomp( TN )*
  CCTransversal@RepnDecomp( T )*
  CharacterOfRepresentation@RepnDecomp( irrep )*
  ClassSum@RepnDecomp( arg )*
  ClassSumCentralizerCoeffs@RepnDecomp( rho, class, cent_basis )*
  ClassSums@RepnDecomp( arg )*
  CohCfgFromPermGroup@RepnDecomp( arg )*
  ComputeUsingMethod@RepnDecomp( rho )*
  ConjugateTranspose@RepnDecomp( mat )*
  ConvertRhoIfNeeded@RepnDecomp( rho )*
  DecomposeCanonicalSummand@RepnDecomp( rho, irrep, V_i )*
  DecomposeCanonicalSummandAlternate@RepnDecomp( rho, irrep, V_i )*
  Drop@RepnDecomp( list, n )*
  ExtractBlock@RepnDecomp( mat, a, b, n )*
  FindCentraliser@RepnDecomp( rho )*
  FuncToHom@RepnDecomp( G, f )*
  GenerateAllBlocks@RepnDecomp( dimension, nblocks )*
  GetParentCC@RepnDecomp( CC )*
  GetSubCC@RepnDecomp( CC, H )*
  GroupSumWithCentralizer@RepnDecomp( rho, cent_basis )*
  InnerProduct@RepnDecomp( A, B )*
  InnerProductOfCharacters@RepnDecomp( chi1, chi2, G )*
  IrrVectorOfRepresentation@RepnDecomp( rho, irr_chars )*
  IrrWithCorrectOrdering@RepnDecomp( G )*
  IrreducibleDecompositionCollectedHybrid@RepnDecomp( rho )*
  IrrepCanonicalSummand@RepnDecomp( rho, irrep )*
  IsCohCfg@RepnDecomp( T )*
  IsDimensions@RepnDecomp( x )*
  IsGInvariant@RepnDecomp( rho, in_space )*
  IsSubCC@RepnDecomp( CC )*
  KroneckerList@RepnDecomp( reps )*
  LinearRepresentationIsomorphismNoProduct@RepnDecomp( rho, tau )*
  MatrixBasis@RepnDecomp( n )*
  MatrixImage@RepnDecomp( p, V )*
  OrbitalMatrix@RepnDecomp( G, representative )*
  OrbitsInfo@RepnDecomp( G, Omega )*
  OrthonormalBasis@RepnDecomp( v )*
  PMatrix@RepnDecomp( rho, irrep )*
  ProjComp@RepnDecomp( T, chi )*
  ProjIrr@RepnDecomp( arg )*
  RandomGroup@RepnDecomp( arg )*
  RandomPermRepresentation@RepnDecomp(  )*
  RandomRepresentation@RepnDecomp( arg )*
  RelevantIrreps@RepnDecomp( rho, irreps )*
  ReplaceBlocks@RepnDecomp( i, blocks, zero_blocks )*
  Replicate@RepnDecomp( elem, n )*
  RepresentationCentralizerPermRep@RepnDecomp( rho )*
  RestrictRep@RepnDecomp( rho, basis )*
  Take@RepnDecomp( list, n )*
  TestBlockDiagonalRepresentation@RepnDecomp( rep, info )*
  TestCanonicalDecomposition@RepnDecomp(  )*
  TestCanonicalDecompsEqual@RepnDecomp( decomp1, decomp2 )*
  TestCentralizerBasis@RepnDecomp(  )*
  TestInvariantDecomposition@RepnDecomp(  )*
  TestIrreducibleDecomposition@RepnDecomp(  )*
  TestMany@RepnDecomp( f, n )*
  TestManyPerm@RepnDecomp( f, n )*
  TransposedMatLILMutable@RepnDecomp( A )*
  WrapMatrix@RepnDecomp( vec, n )*
  WrapRep@RepnDecomp( rho, irreps )*
  doCoeffsComputation@RepnDecomp( T, ci, cj, I, J, k )*
  doCoeffsPerCCElement@RepnDecomp( TN, k )*
  indexInLeftFiber@RepnDecomp( TN, onum, blk )*

### Variables checked for "repndecomp", ver. 1.0.1
===========================================
```

**Comment by alex-konovalov** [comment]
The next report is from `make testpackagesload`. First, there are warnings:
```
#I  RepnDecomp: Do not call `LoadPackage( "grape", ... )' in the package file
#I              /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest-drop-in/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovacs/GAP-pkg-update-stable-snapshot/pkg/RepnDecomp-1.0.1/lib/cohcfg/classmatr.gi,
#I              use `IsPackageMarkedForLoading' instead
#I  GRAPE: entering LoadPackage 
#I  GRAPE: return from LoadPackage, package was already loaded
#I  RepnDecomp: Do not call `LoadPackage( "io", ... )' in the package file
#I              /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest-drop-in/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovacs/GAP-pkg-update-stable-snapshot/pkg/RepnDecomp-1.0.1/lib/serre.gi,
#I              use `IsPackageMarkedForLoading' instead
```
Indeed, if you need some package in package code, there is a dependencies mechanism to specify  that in PackageInfo.g, and if the package is suggested, and some code should be loaded optionally, then `IsPackageMarkedForLoading` is for that purpose.

**Comment by alex-konovalov** [comment]
Finally, the package breaks `LoadAllPackages();` test: if SONATA package is loaded after RepnDecomp, then there is an error:
```
#I  SONATA: start reading file 'read.g'
Error, Variable: 'BlockDiagonalMatrix' is read only
```
and if the other way round, then the error is
```

**Comment by kaashif** [comment]
Great, thanks for running these tests. I will fix these errors as soon as possible.

**Comment by kaashif** [comment]
I think I fixed your issues. In particular, `LoadAllPackages()` works for me (in particular, with SONATA), which I think I fixed in this commit: https://github.com/gap-packages/RepnDecomp/commit/b99c2c2e6d438d683c724d27aaf2e16e05b27012. I haven't finished writing extensive non-flaky tests, so it's possible there's still something broken.

**Comment by alex-konovalov** [comment]
@kaashif Thanks. https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.11-devel/jobs/648427546 now shows RepnDecomp tests passing. I will rerun the compatibility tests with other packages again.

**Comment by alex-konovalov** [comment]
@kaashif the website still provides RepnDecomp-1.0.1 which I have tested already and reported above. if you believe that the problems are fixed, please publish a new release, and I will pick it up for tests then.

**Comment by kaashif** [comment]
New version published. The manual examples, new non-flaky tests, and some changes from @alex-konovalov and @dimpase are now published in version 1.1.0: https://gap-packages.github.io/RepnDecomp/. Let me know what you think.

**Comment by alex-konovalov** [comment]
Thanks @kaashif - I've started a round of tests in Jenkins, will check when it will be completed.

**Comment by alex-konovalov** [comment]
@kaashif those tests were completed, now merging this PR to go to the next step tomorrow.

**Comment by alex-konovalov** [comment]
@kaashif (CC @VivianePons) the package is picked up for the redistribution with GAP - next round of testing is underway:
```
* RepnDecomp - new version 1.1.0 discovered!!!
  ============================================
  Getting new archives from 
  https://github.com/gap-packages/RepnDecomp/releases/download/v1.1.0/RepnDeco\
mp-1.1.0[ ".tar.bz2", ".tar.gz" ]
  unpacking RepnDecomp-1.1.0.tar.gz
  Validation of the info file successful!
WARNING (RepnDecomp): has status dev
which is is not one of accepted/submitted/deposited
  Package RepnDecomp 1.1.0 from 15/02/2020 has dependencies:
  * NeededOtherPackages [ [ "GAPDoc", ">= 1.6.1" ], [ "GRAPE", ">= 4.8.1" ] ]
  * GAP >= 4.10
  * SuggestedOtherPackages [ [ "IO", ">= 4.7.0" ] ]
  finding text files  . . .

=====================text files==========================
RepnDecomp-1.1.0/README.md
RepnDecomp-1.1.0/read.g
RepnDecomp-1.1.0/LICENSE
RepnDecomp-1.1.0/init.g
RepnDecomp-1.1.0/PackageInfo.g
RepnDecomp-1.1.0/paper.bib
RepnDecomp-1.1.0/makedoc.g
RepnDecomp-1.1.0/examples/unitary.g
RepnDecomp-1.1.0/examples/isomorphism.g
RepnDecomp-1.1.0/examples/serre.g
RepnDecomp-1.1.0/old_tst/BlockDiagonalRepresentationFastCanonical.tst
RepnDecomp-1.1.0/old_tst/CharacterInnerProduct.tst
RepnDecomp-1.1.0/old_tst/RepresentationCentralizer.tst
RepnDecomp-1.1.0/old_tst/RestrictRep.tst
RepnDecomp-1.1.0/old_tst/IrrepCanonicalSummand.tst
RepnDecomp-1.1.0/old_tst/LDLDecomposition.tst
RepnDecomp-1.1.0/old_tst/BlockDiagonalBasis.tst
RepnDecomp-1.1.0/old_tst/DecomposeCanonicalSummandFast.tst
RepnDecomp-1.1.0/old_tst/Drop.tst
RepnDecomp-1.1.0/old_tst/BlockDiagonalMatrix.tst
RepnDecomp-1.1.0/old_tst/ClassSumCentralizer.tst
RepnDecomp-1.1.0/old_tst/TensorProductRepLists.tst
RepnDecomp-1.1.0/old_tst/BlockDiagonalRepresentationFast.tst
RepnDecomp-1.1.0/old_tst/OrbitalMatrix.tst
RepnDecomp-1.1.0/old_tst/GenerateAllBlocks.tst
RepnDecomp-1.1.0/old_tst/ExtractBlock.tst
RepnDecomp-1.1.0/old_tst/Replicate.tst
RepnDecomp-1.1.0/old_tst/Take.tst
RepnDecomp-1.1.0/old_tst/GroupSumBSGS.tst
RepnDecomp-1.1.0/old_tst/RepresentationCentralizerBlocks.tst
RepnDecomp-1.1.0/old_tst/DecomposeCanonicalSummand.tst
RepnDecomp-1.1.0/old_tst/UnitaryRepresentation.tst
RepnDecomp-1.1.0/old_tst/IrreducibleDecomposition.tst
RepnDecomp-1.1.0/old_tst/OrthonormalBasis.tst
RepnDecomp-1.1.0/old_tst/CanonicalDecomposition.tst
RepnDecomp-1.1.0/old_tst/TensorProduct.tst
RepnDecomp-1.1.0/old_tst/IrreducibleDecompositionCollectedHybrid.tst
RepnDecomp-1.1.0/old_tst/IrreducibleDecompositionCollected.tst
RepnDecomp-1.1.0/old_tst/BlockDiagonalRepresentation.tst
RepnDecomp-1.1.0/old_tst/MatrixImage.tst
RepnDecomp-1.1.0/old_tst/DecomposeCharacter.tst
RepnDecomp-1.1.0/old_tst/IrrepToCharacter.tst
RepnDecomp-1.1.0/doc/_Chapter_Algorithms_for_unitary_representations.xml
RepnDecomp-1.1.0/doc/chap3.html
RepnDecomp-1.1.0/doc/chap1_mj.html
RepnDecomp-1.1.0/doc/times.css
RepnDecomp-1.1.0/doc/chooser.html
RepnDecomp-1.1.0/doc/chap2.txt
RepnDecomp-1.1.0/doc/chap3.txt
RepnDecomp-1.1.0/doc/chap1.txt
RepnDecomp-1.1.0/doc/RepnDecomp.xml
RepnDecomp-1.1.0/doc/chap6.txt
RepnDecomp-1.1.0/doc/_Chapter_Introduction.xml
RepnDecomp-1.1.0/doc/chap5_mj.html
RepnDecomp-1.1.0/doc/chapInd.html
RepnDecomp-1.1.0/doc/chap5.txt
RepnDecomp-1.1.0/doc/chap6.html
RepnDecomp-1.1.0/doc/title.xml
RepnDecomp-1.1.0/doc/chap0.txt
RepnDecomp-1.1.0/doc/nocolorprompt.css
RepnDecomp-1.1.0/doc/chap0_mj.html
RepnDecomp-1.1.0/doc/manual.css
RepnDecomp-1.1.0/doc/chap4_mj.html
RepnDecomp-1.1.0/doc/_Chapter_Computing_decompositions_of_representations.xml
RepnDecomp-1.1.0/doc/chap4.txt
RepnDecomp-1.1.0/doc/chap3_mj.html
RepnDecomp-1.1.0/doc/chap0.html
RepnDecomp-1.1.0/doc/chapInd.txt
RepnDecomp-1.1.0/doc/chap2.html
RepnDecomp-1.1.0/doc/ragged.css
RepnDecomp-1.1.0/doc/chap6_mj.html
RepnDecomp-1.1.0/doc/_Chapter_Centralizer_commutant_rings.xml
RepnDecomp-1.1.0/doc/chapInd_mj.html
RepnDecomp-1.1.0/doc/_AutoDocMainFile.xml
RepnDecomp-1.1.0/doc/chap4.html
RepnDecomp-1.1.0/doc/chap2_mj.html
RepnDecomp-1.1.0/doc/chap1.html
RepnDecomp-1.1.0/doc/_Chunks.xml
RepnDecomp-1.1.0/doc/_Chapter_Isomorphisms_between_representations.xml
RepnDecomp-1.1.0/doc/chap5.html
RepnDecomp-1.1.0/doc/toggless.css
RepnDecomp-1.1.0/doc/_Chapter_Miscellaneous_useful_functions.xml
RepnDecomp-1.1.0/doc/lefttoc.css
RepnDecomp-1.1.0/lib/tensor.gi
RepnDecomp-1.1.0/lib/isomorphism.gd
RepnDecomp-1.1.0/lib/methsel.gi
RepnDecomp-1.1.0/lib/centralizer.gi
RepnDecomp-1.1.0/lib/unitary.gi
RepnDecomp-1.1.0/lib/mymethod.gi
RepnDecomp-1.1.0/lib/serre.gi
RepnDecomp-1.1.0/lib/filters.gd
RepnDecomp-1.1.0/lib/groupsum.gd
RepnDecomp-1.1.0/lib/isomorphism.gi
RepnDecomp-1.1.0/lib/mymethod.gd
RepnDecomp-1.1.0/lib/serre.gd
RepnDecomp-1.1.0/lib/block_diagonalize.gi
RepnDecomp-1.1.0/lib/centralizer.gd
RepnDecomp-1.1.0/lib/utils.gd
RepnDecomp-1.1.0/lib/aaa_manual.gd
RepnDecomp-1.1.0/lib/block_diagonalize.gd
RepnDecomp-1.1.0/lib/unitary.gd
RepnDecomp-1.1.0/lib/filters.gi
RepnDecomp-1.1.0/lib/groupsum.gi
RepnDecomp-1.1.0/lib/tensor.gd
RepnDecomp-1.1.0/lib/utils.gi
RepnDecomp-1.1.0/lib/cohcfg/misc.gi
RepnDecomp-1.1.0/lib/cohcfg/classsum.gi
RepnDecomp-1.1.0/lib/cohcfg/SubgroupCC.gi
RepnDecomp-1.1.0/lib/cohcfg/classmatr.gi
RepnDecomp-1.1.0/tst/testall.g
RepnDecomp-1.1.0/tst/repndecomp03.tst
RepnDecomp-1.1.0/tst/repndecomp02.tst
RepnDecomp-1.1.0/tst/repndecomp04.tst
RepnDecomp-1.1.0/tst/repndecomp01.tst

=====================end of the list of text files=======
=====================binary files========================
RepnDecomp-1.1.0/paper.md
RepnDecomp-1.1.0/makedoc.sh
RepnDecomp-1.1.0/doc/toggless.js
RepnDecomp-1.1.0/doc/rainbow.js
RepnDecomp-1.1.0/doc/manual.js
RepnDecomp-1.1.0/doc/RepnDecomp.toc
RepnDecomp-1.1.0/doc/manual.pdf
RepnDecomp-1.1.0/doc/manual.six

=====================end of the list of binary files=====
```

**Comment by dimpase** [comment]
Great, thanks for the update.
Travelling this and the next week, might not reply quickly.

**Pull request merged**
