### PR TITLE
Update currentPackageInfoURLList

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@james-d-mitchell thanks, but this will not work - you need to use MOVE command as explained in the comment at the beginning of this file.

**Comment by james-d-mitchell** [comment]
Oh sorry, will update tomorrow!

**Comment by james-d-mitchell** [comment]
@alex-konovalov updated I hope according to the instruction, please let me know if something is still not correct.

**Review by alex-konovalov — APPROVED** [review]
Looks good now, thanks @james-d-mitchell!

**Pull request merged**
